export const ADAMA_BRAND_PROFILE = Object.freeze({
  id: "adama",
  organization: "ADAMA",
  audience: "Young Russian-speaking new immigrants in Israel",
  languages: ["ru", "he", "en"],
  primaryLanguage: "ru",
  tone: ["fresh", "young", "bold", "warm", "community-first"],
  visual: {
    status: "adama_brand_source_pending",
    targetPalette: ["lime", "green", "black", "white"],
    observedLegacyPalette: {
      coralOrange: "#FF7657",
      skyBlue: "#86BDD2",
      warmWhite: "#F4F4F6",
      black: "#000000",
    },
    typography: "oversized bold display type with compact supporting copy",
    direction: "minimal, emotional, playful, community-first",
    motifs: [
      "rounded blocks",
      "simple geometric shapes",
      "large dates",
      "human photography",
      "Jewish symbols used respectfully",
    ],
    rules: [
      "Use one dominant message per frame",
      "Keep essential text inside mobile-safe margins",
      "Maintain high contrast and readable Russian/Hebrew typography",
      "Do not stretch, recolor, or crowd the ADAMA logo",
      "Do not use CBA Young templates, logos, or palette in ADAMA content",
    ],
  },
  pillars: [
    "aliyah and integration",
    "Hebrew and Israeli slang",
    "Jewish holidays and Shabbat",
    "Jewish thought and the Lubavitcher Rebbe",
    "community events and city groups",
    "new immigrant memes",
  ],
  reviewRules: [
    "Do not invent religious quotations or historical claims",
    "Use absolute dates for events and holidays",
    "Keep the CTA concrete and community-oriented",
    "Avoid manipulative virality and political rage bait",
    "Publishing always requires human approval",
  ],
});
